delay:
  checktickdelay: 5
  compasstickdelay: 20

messages:
  reloadconfig: "§bReloading Config!"
  enabled: "§b[BiomeRace]: Plugin is enabled!"
  disabled: "§b[BiomeRace]: Plugin is disabled."
  tabcompleteinstanceload: "§bCreating BiomeRace Tab Instance"
  configinstanceload: "§bCreating Config Instance"
  translatedtextload: "§bTranslated Text Loaded"
  updatedelayhelp: "§bUse /updatedelay to change how fast the game will update the location of the players. Input values are measured in ticks."
  firsttobiome: "§b %s found the biome first!"
  ggmsg: "§bggs"
  biomeactionbar: "§6Current Biome: %s - Looking for: %s"
  trackingplayer: "§6 Currently tracking: %s - Distance: %s"
  onlineplayers: "§bPlayers Online: %s"
  racestarttitle: "§bFind a %s biome!"
  racestartsubtitle: "§bFind the biome before your opponent!"
  racecanceltitle: "§bThe race has been cancelled."
  racecancelsubtitle: ""
  racestatus: "§bLooking for a %s biome currently."
  checkupdatedesription: "§bThe tick delay for checking the players' location has been set to %s ticks. (A tick is a 20th of a second.)"
  compassupdatedesription: "§bThe tick delay for updating the compass has been set to %s ticks. (A tick is a 20th of a second.)"
  updatedelayusage: "§bPlease specify which component of the plugin you would like to change the update time for, then type the amount of ticks you'd like to change."
  playerjoin: "§bWelcome :D"





  