delay:
  actionbartickdelay: 5
  racechecktickdelay: 100

messages:
  reloadconfig: "§b Reloading Config!"
  endabled: "§b[BiomeRace]: Plugin is enabled!"
  disabled: "§b[BiomeRace]: Plugin is disabled."
  tabcompleteinstanceload: "§bCreating BiomeRace Tab Instance"
  configinstanceload: "§bCreating Config Instance"
  translatedtextload: "§bTranslated Text Loaded"
  updatedelayhelp: "§bUse §e/updatedelay§b §2ab §c<ticks>§b for changing the action bar tick delay and use §e/updatedelay§b §2rc §c<ticks>§b for changing the Biome Race Biome Update Check tick delay, this means how fast it updates."
  firsttobiome: "§b %s found the biome first!"
  ggmsg: "§3ggs"
  currentbiome: "§3 Current Biome: %s"
  lookforbiome: "§5 Looking For: %s"
  onlineplayers: "§bPlayers Online: %s"
  racestarttitle: "§bFind a %s biome!"
  racestartsubtitle: "§3Find the biome before your opponent!"
  racecanceltitle: "§bThe race has been cancelled."
  racecancelsubtitle: ""
  racestatus: "§bLooking for a %s biome currently."
  racecheckupdatedesription: "§bThe tick delay for checking Winner has been set to %s ticks. (A tick is a 20th of a second.)"
  actionbarupdatedesription: "§bThe tick delay for updating the action bar has been set to %s ticks. (A tick is a 20th of a second.)"
  updatedelayinputless: "§cSorry But you need so Specify What Type you want to Change and set an amount.§b Action Bar Value: %s , Race Check Value: %s"





  