messages:
  reload: "§b Reloading Config!"
  endabled: "§b[BiomeRace]: Plugin is enabled!"
  disabled: "§b[BiomeRace]: Plugin is disabled."
  tabcompleteinstanceload: "§bCreating BiomeRace Tab Instance"
  firsttobiome: "§b %s found the biome first!"
  ggmsg: "§3ggs"
  currentbiome: "§3 Current Biome: %s"
  lookforbiome: "§5 Looking For: %s"
